language: elixir
elixir:
- 1.3.4
otp_release:
- 18.0

sudo: false

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database meebuss;' -U postgres

install:
- mix local.hex --force
- mix local.rebar --force
- mix deps.get

script: mix test

notifications:
  recipients:
  - rob@datachomp.com
